version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - save_cache:
          paths:
            - /src/node_modules
          key: "packages"
  
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "packages"
      - run: npm run test
  
  analyze: 
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  pipeline:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires:
            - test